### ISSUE TITLE
configuration file with wrong values

### ISSUE THREAD

**Issue by AdrienHorgnies** [bastienmichaux/db-importer#17]
I thought I handled that nicely but it seems using a wrong value in the configuration file ends in software failing when it should really just ask the correct value to the user.

ex:
Configuration file :

```json
{
	"dbms": "msql",
	"host": "192.168.32.2",
	"port": "3306",
	"user": "root",
	"password": "password",
	"schema": "elearning"
}
```

Notice the typo in the **dbms**. It should result in the software asking the dbms to the user through `inquirer`.
But instead, this happens :
TypeError: Cannot read property 'defaultPort' of undefined
TypeError: Cannot read property 'driver' of undefined
(node:10384) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot convert undefined or null to object

tested against `12815b2 (origin/dev, dev) Merge branch 'feature/no-console' into dev`

**Comment by AdrienHorgnies** [comment]
I'm not sure but I've got an idea : delete any value that didn't pass the validation immediately to avoid subsequent call to use it.

**Comment by bastienmichaux** [comment]
We can simply check the type of our parameters. Defensive programming, never trust your parameters.

**Comment by AdrienHorgnies** [comment]
It's more complex than that; Here we have a value that failed validation, and thus **has already been thoroughly checked**.
